# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/access_token_refresh_token_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=none

# Secret Key to sign Access Token
app.jwt.secret=3d93YIZmVPUVIaOw+C6jM1b9NR/LZGhG/f60oKplV8VFM2Bb7O2zPZDgbxV9YEdv68eOm1E6yr5ITeqdPS4HoQ==

# Access Token Expiration (15 minutes)
app.jwt.access-expires-in-mili-seconds=900000

# Refresh Token Expiration (7 days)
app.jwt.refresh-expires-in-mili-seconds=604800000